version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Java JDK 17...
      - REPOSITORY_URI=977109810725.dkr.ecr.us-east-1.amazonaws.com/smartfin-backend
      - ARTIFACT=smartfin-backend
      - ARTIFACT_TYPE=.jar 
      - TAG_NAME=$REPOSITORY_URI:$ARTIFACT

  pre_build:
    commands:
      - echo Starting pre-build steps...
      - java -version # Verify Java version
      - ./gradlew check

  build:
    commands:
      - echo Building the Spring Boot application...
      - ./gradlew clean build # Compiles your Spring Boot application
      - echo Building the docker image
      #- docker build -f src/main/docker/Dockerfile -t $TAG_NAME .

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files: build/libs/* # Adjust the path to where your Gradle build outputs the JAR file

cache:
  paths:
    - '/root/.gradle/caches/**/*' # Cache Gradle dependencies to speed up future builds
    - '/root/.gradle/wrapper/**/*' # Cache the Gradle wrapper
