version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 20
    commands:
      - echo Installing Java JDK 17...
      - ARTIFACT=smartfin-backend
      - ARTIFACT_TYPE=.jar 
      - TAG_NAME=$REPOSITORY_URI:$ARTIFACT

  pre_build:
    commands:
      - echo Starting pre-build steps...
      - java -version # Verify Java version
      - ./gradlew check
      - aws --version
      - echo Logging in... 
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 977109810725.dkr.ecr.us-east-1.amazonaws.com
      # Get commit hash value to tag the image
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      # Replace with your application name
      - APPLICATION_NAME=smartfin-backend
      - REPOSITORY_URI=977109810725.dkr.ecr.us-east-1.amazonaws.com/$APPLICATION_NAME

  build:
    commands:
      - echo Building the Spring Boot application...
      - ./gradlew clean build # Compiles your Spring Boot application
      - echo Building the Docker image... 
      #- docker build -t $APPLICATION_NAME:$IMAGE_TAG .
      - docker build -t smartfin-backend .
      # - docker tag $APPLICATION_NAME:$IMAGE_TAG $APPLICATION_NAME:$IMAGE_TAG
      - docker tag smartfin-backend:latest 977109810725.dkr.ecr.us-east-1.amazonaws.com/smartfin-backend:latest
      - echo "Listing contents of build/libs directory..."
      - ls -al build/libs

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Build completed on `date` 
      - echo pushing to repo
      #- docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push 977109810725.dkr.ecr.us-east-1.amazonaws.com/smartfin-backend:latest
      - printf '[{"name":"SpringBootAppContainer", "imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: 
    - build/libs/* # Adjust the path to where your Gradle build outputs the JAR file
    - imagedefinitions.json

cache:
  paths:
    - '/root/.gradle/caches/**/*' # Cache Gradle dependencies to speed up future builds
    - '/root/.gradle/wrapper/**/*' # Cache the Gradle wrapper
