version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Java JDK 17...

  pre_build:
    commands:
      - echo Starting pre-build steps...
      - java -version # Verify Java version
      - ./gradlew check

  build:
    commands:
      - echo Building the Spring Boot application...
      - ./graldew clean build # Compiles your Spring Boot application

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/libs/*.jar # Adjust the path to where your Gradle build outputs the JAR file

cache:
  paths:
    - '/root/.gradle/caches/**/*' # Cache Gradle dependencies to speed up future builds
    - '/root/.gradle/wrapper/**/*' # Cache the Gradle wrapper
