name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Build with Gradle Wrapper
      run: ./gradlew build
    - name: Build Docker Image
      run: docker build -t smartfin-backend .
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Tag Docker Image
      run: docker tag smartfin-backend muki1992/smartfin-backend
    - name: Push Docker Image to Docker Hub
      run: docker push muki1992/smartfin-backend
